import { addImports, addPlugin, addTemplate, createResolver, defineNuxtModule } from "nuxt/kit";
import type { ModuleOptions } from "./types";

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "dayjs",
    configKey: "dayjs",
    compatibility: {
      nuxt: ">=3",
    },
  },
  defaults: {
    locales: [],
    plugins: ["relativeTime", "utc"],
    externalPlugins: [],
    defaultLocale: undefined,
    defaultTimezone: undefined,
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);
    options.plugins = [...new Set(options.plugins)];
    options.externalPlugins = [...new Set(options.externalPlugins)];

    if (options.defaultTimezone && !options.plugins.includes("timezone"))
      throw new Error("You must include the timezone plugin in order to set a default timezone");

    addPlugin(resolver.resolve("./runtime/plugin"));

    nuxt.options.alias["#dayjs"] = resolver.resolve("./runtime/composables/dayjs");
    addImports({
      name: "useDayjs",
      as: "useDayjs",
      from: nuxt.options.alias["#dayjs"],
    });

    addImports({
      name: "dayjs",
      as: "dayjs",
      from: nuxt.options.alias["#dayjs"],
    });

    addTemplate({
      filename: "dayjs.imports.mjs",
      getContents: () => generateImports(options),
      write: true,
    });

    // Add dayjs plugin types
    nuxt.hook("prepare:types", ({ references }) => {
      if (options.plugins) {
        const plugins = options.plugins.map((p) => ({ types: `dayjs/plugin/${p}` }));
        references.push(...plugins);
      }
      if (options.externalPlugins) {
        const externalPlugins = options.externalPlugins.map((p) => ({ types: p.package }));
        references.push(...externalPlugins);
      }
    });
  },
});

function generateImports({
  locales,
  plugins,
  externalPlugins,
  defaultLocale,
  defaultTimezone,
}: ModuleOptions) {
  return `
// Generated by dayjs-module
import dayjs from 'dayjs'
import updateLocale from 'dayjs/plugin/updateLocale'

${locales?.map((locale) => `import 'dayjs/locale/${locale}'`).join("\n")}
${plugins?.map((plugin) => `import ${plugin} from 'dayjs/plugin/${plugin}'`).join("\n")}
${externalPlugins?.map((plugin) => `import ${plugin.name} from '${plugin.package}'`).join("\n")}

dayjs.extend(updateLocale)

${plugins?.map((plugin) => `dayjs.extend(${plugin})`).join("\n")}
${externalPlugins?.map((plugin) => `dayjs.extend(${plugin.name}, ${JSON.stringify(plugin.option)})`).join("\n")}
${defaultTimezone ? `dayjs.tz.setDefault('${defaultTimezone}')` : ""}

// defaultLocale: ${JSON.stringify(defaultLocale)}

${
  defaultLocale
    ? `
dayjs.updateLocale(${JSON.stringify(defaultLocale).replace(/^\[|\]$/g, "")})
dayjs.locale('${typeof defaultLocale === "string" ? defaultLocale : defaultLocale[0]}')
`
    : ""
}

export default dayjs
`;
}
